#!php
<?php


/**
 * *******************************************************
 * *                                                     *
 * *    Luna V2;                                         *
 * *                                                     *
 * *   Launch day                                        *
 * *                                                     *
 * *******************************************************
 */

namespace Luna ;

use Luna\Core\Luna;

require_once 'src/core/Luna.php';

$app = new Luna();

$app->launch($argv);


//var_dump(posix_getpwuid(posix_geteuid())['name']);

//shell_exec("run.bat ");
